# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 41b0b37c621b759efb194faeaf7c6bfca50f7d57568c21837697bd18c1cff65a81e92e795d746eddd3708c798e4a399778b51a5a05f1aa8b3c450ca1df62bb13

test:
  secret_key_base: 6f857490f6b5c54f11e88689f367e4bce6d6acfadae94b1f6d0be9164112d96333f85a87005ad9203717f5c82ad6266d9a91a28bb712398d8bda1ff6649267ee

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
